
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;



import Model.MedicalRecord;
import Service.MedicalRecordService;

import static com.oracle.util.Checksums.update;

import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author Thierry
 */
public class MedicalForms extends javax.swing.JFrame {

    /**
     * Creates new form MedicalForms
     */
    public MedicalForms() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        diagnosisTxt = new javax.swing.JTextField();
        treatmentTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        recordidTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AddTxt = new javax.swing.JButton();
        updateTxt = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        patientCombo = new javax.swing.JComboBox<>();
        dateTxt = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        medicalrecordlistTxt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(712, 510));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setMinimumSize(new java.awt.Dimension(730, 480));
        jPanel2.setPreferredSize(new java.awt.Dimension(730, 490));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel2.setText("Diagnosis");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel3.setText("Treatment");

        diagnosisTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosisTxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel4.setText("Record Id");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel5.setText("Date");

        AddTxt.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        AddTxt.setText("Add");
        AddTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddTxtMouseClicked(evt);
            }
        });
        AddTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTxtActionPerformed(evt);
            }
        });

        updateTxt.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        updateTxt.setText("Update");
        updateTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTxtActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(204, 0, 51));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        exit.setText("Exit");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel7.setText("Patient");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(622, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(43, 43, 43))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(treatmentTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(diagnosisTxt)
                            .addComponent(recordidTxt)
                            .addComponent(patientCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(updateTxt)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(exit)
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(recordidTxt)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diagnosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treatmentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 720, 500);

        medicalrecordlistTxt.setText("Medical Records List");
        medicalrecordlistTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        medicalrecordlistTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        medicalrecordlistTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicalrecordlistTxtMouseClicked(evt);
            }
        });
        jMenuBar1.add(medicalrecordlistTxt);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diagnosisTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosisTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosisTxtActionPerformed

    private void AddTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTxtActionPerformed
   
                            
    }//GEN-LAST:event_AddTxtActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    
    }//GEN-LAST:event_exitActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here
        
        this.setVisible(false);
    
    // Create a new instance of the home window and make it visible
  //  new home().setVisible(true);
    }//GEN-LAST:event_exitMouseClicked

    private void AddTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTxtMouseClicked
        // TODO add your handling code here:
            if (recordidTxt.getText().isEmpty() || diagnosisTxt.getText().isEmpty() ||
        treatmentTxt.getText().isEmpty() || dateTxt.getDate() == null) {
        
        JOptionPane.showMessageDialog(this, "Please fill in all fields");
            }else {
                try{
                    Registry registry = LocateRegistry.getRegistry("127.0.0.1", 5000);
                   MedicalRecordService  service = (MedicalRecordService)registry.lookup("medicalrecord");
                    MedicalRecord theMedicalRecord = new MedicalRecord ();
                    theMedicalRecord .setRecord_id(Integer.parseInt(recordidTxt.getText()));
                    theMedicalRecord.setDiagnosis(diagnosisTxt.getText());
                    theMedicalRecord.setTreatment( treatmentTxt.getText());
                    
                        // Convert java.util.Date to java.sql.Date
                   java.util.Date utilDate = dateTxt.getDate();
                   java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                   theMedicalRecord.setDate(sqlDate);
                 
                    
            
            MedicalRecord medObj = service.registerMedicalRecord(theMedicalRecord);
            JOptionPane.showMessageDialog(this , "Registered Successfull");
            
        }catch(Exception ex){ 
            ex.printStackTrace();
        }  
    
            }
    }//GEN-LAST:event_AddTxtMouseClicked

    private void updateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTxtActionPerformed
        // TODO add your handling code here:        
           if (recordidTxt.getText().isEmpty() || diagnosisTxt.getText().isEmpty() ||
        treatmentTxt.getText().isEmpty() || dateTxt.getDate() == null ) {
        
        JOptionPane.showMessageDialog(this, "Please fill in all fields");
            }else {
                try{
           Registry registry = LocateRegistry.getRegistry("127.0.0.1", 5000);
                   MedicalRecordService  service = (MedicalRecordService)registry.lookup("medicalrecord");
                    MedicalRecord theMedicalRecord = new MedicalRecord ();
                    theMedicalRecord .setRecord_id(Integer.parseInt(recordidTxt.getText()));
                    theMedicalRecord.setDiagnosis(diagnosisTxt.getText());
                    theMedicalRecord.setTreatment( treatmentTxt.getText());
                    
                        // Convert java.util.Date to java.sql.Date
                   java.util.Date utilDate = dateTxt.getDate();
                   java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                   theMedicalRecord.setDate(sqlDate);
                 
            MedicalRecord medObj = service.updateMedicalRecord(theMedicalRecord);
            JOptionPane.showMessageDialog(this , "Medical Record Updated Successfull");
            
        }catch(Exception ex){ 
            ex.printStackTrace();
        }  
    
            }  
          

        
    }//GEN-LAST:event_updateTxtActionPerformed

    private void medicalrecordlistTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicalrecordlistTxtMouseClicked
        // TODO add your handling code here:
          setVisible(false);
            new MedicalRecordslist().setVisible(true);
    }//GEN-LAST:event_medicalrecordlistTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicalForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicalForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicalForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicalForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicalForms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTxt;
    private com.toedter.calendar.JDateChooser dateTxt;
    private javax.swing.JTextField diagnosisTxt;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu medicalrecordlistTxt;
    private javax.swing.JComboBox<String> patientCombo;
    private javax.swing.JTextField recordidTxt;
    private javax.swing.JTextField treatmentTxt;
    private javax.swing.JButton updateTxt;
    // End of variables declaration//GEN-END:variables
}
