
package View;
import Model.Patient;
import Service.PatientService;
import static com.oracle.util.Checksums.update;

import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author Thierry
 */
public class PatientManagement extends javax.swing.JFrame {

    /**
     * Creates new form PatientManagement
     */
    public PatientManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
                                              
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientIdTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        patientnameTxt = new javax.swing.JTextField();
        breedTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        ownerTxt = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        AddTxt = new javax.swing.JButton();
        updateTxt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        animalpatientlistTxt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Management");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel2.setText("Name");

        patientIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdTxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel3.setText("ID");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel4.setText("Breed");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel5.setText("Age");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel6.setText("Owner");

        patientnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientnameTxtActionPerformed(evt);
            }
        });

        ageTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtActionPerformed(evt);
            }
        });

        ownerTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerTxtActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 0, 51));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        exit.setText("Exit");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        AddTxt.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        AddTxt.setText("Add");
        AddTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddTxtMouseClicked(evt);
            }
        });
        AddTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTxtActionPerformed(evt);
            }
        });

        updateTxt.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        updateTxt.setText("Update");
        updateTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateTxtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateTxtMousePressed(evt);
            }
        });
        updateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(AddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(breedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(ageTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ownerTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                            .addComponent(patientnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(patientIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(updateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(exit)
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(breedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddTxt)
                    .addComponent(updateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        animalpatientlistTxt.setText("Animal Patient List");
        animalpatientlistTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        animalpatientlistTxt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        animalpatientlistTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                animalpatientlistTxtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                animalpatientlistTxtMousePressed(evt);
            }
        });
        animalpatientlistTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalpatientlistTxtActionPerformed(evt);
            }
        });
        jMenuBar1.add(animalpatientlistTxt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIdTxtActionPerformed

    private void ageTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtActionPerformed

    private void ownerTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerTxtActionPerformed

    private void AddTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTxtActionPerformed
        
    if (patientIdTxt.getText().isEmpty() || patientnameTxt.getText().isEmpty() ||
        breedTxt.getText().isEmpty() || ageTxt.getText().isEmpty() ||
        ownerTxt.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields");
         
    }else {
        try{
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 5000);
            PatientService service = (PatientService)registry.lookup("patient");
            Patient thePatient = new Patient();
            thePatient.setPatientId(Integer.parseInt(patientIdTxt.getText()));
            thePatient.setPatientName(patientnameTxt.getText());
            thePatient.setPatientBreed(breedTxt.getText());
            thePatient.setPatientAge(Integer.parseInt(ageTxt.getText()));
            thePatient.setPatientOwner(ownerTxt.getText());
            
            Patient patObj = service.registerPatient(thePatient);
            JOptionPane.showMessageDialog(this , "Registered Successfull");
            
        }catch(Exception ex){ 
            ex.printStackTrace();
        }
        
        
    }
     
    }//GEN-LAST:event_AddTxtActionPerformed

    private void patientnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientnameTxtActionPerformed
    
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_exitActionPerformed

    private void AddTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddTxtMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
                  // TODO add your handling code here:
         this.setVisible(false);
    
    // Create a new instance of the home window and make it visible
  //  new home().setVisible(true);
    }//GEN-LAST:event_exitMouseClicked

    private void animalpatientlistTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animalpatientlistTxtMouseClicked
        // TODO add your handling code here:
       setVisible(false);
            new AnimalPatient_list().setVisible(true);
    }//GEN-LAST:event_animalpatientlistTxtMouseClicked

    private void animalpatientlistTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalpatientlistTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalpatientlistTxtActionPerformed

    private void animalpatientlistTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animalpatientlistTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalpatientlistTxtMousePressed

    private void updateTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTxtMouseClicked

    private void updateTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTxtMousePressed

    private void updateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTxtActionPerformed
        // TODO add your handling code here:
        if (patientIdTxt.getText().isEmpty() || patientnameTxt.getText().isEmpty() ||
            breedTxt.getText().isEmpty() || ageTxt.getText().isEmpty() ||
            ownerTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields");

        }else {
            try{
                Registry registry = LocateRegistry.getRegistry("127.0.0.1", 5000);
                PatientService service = (PatientService)registry.lookup("patient");
                Patient thePatient = new Patient();
                thePatient.setPatientId(Integer.parseInt(patientIdTxt.getText()));
                thePatient.setPatientName(patientnameTxt.getText());
                thePatient.setPatientBreed(breedTxt.getText());
                thePatient.setPatientAge(Integer.parseInt(ageTxt.getText()));
                thePatient.setPatientOwner(ownerTxt.getText());

                Patient patObj = service.updatePatient(thePatient);
                JOptionPane.showMessageDialog(this , "Data Update Successfull");

            }catch(Exception ex){
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_updateTxtActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
     {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientManagement().setVisible(true);
            }
        
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTxt;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JMenu animalpatientlistTxt;
    private javax.swing.JTextField breedTxt;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField ownerTxt;
    private javax.swing.JTextField patientIdTxt;
    private javax.swing.JTextField patientnameTxt;
    private javax.swing.JButton updateTxt;
    // End of variables declaration//GEN-END:variables
}
